### ISSUE TITLE
[BUG] Updating existing source yml removes pre-existing quotes from description

### ISSUE THREAD

**Issue by jaredx435k2d0** [datacoves/dbt-coves#297]
**Describe the bug**
Pre-exising contents of schema.yml
```
version: 2
sources:
  - name: my_source_name
    database: my_database_name
    description: 'here is a test source description'
    tables:
      - name: my_table_name
        description: 'here is a test table description'
```

Command: 
`dbt-coves generate sources --database my_database_name --schemas my_schema_name --update-strategy update`

Contents of schema.yml after executing command:

```
version: 2
sources:
  - name: my_source_name
    database: my_database_name
    description: here is a test source description
    tables:
      - name: my_table_name
        description: here is a test table description
```

**To Reproduce**
Steps to reproduce the behaviour:

1. Create source file with at least one description
2. Run command `dbt-coves generate sources --database my_database_name --schemas my_schema_name --update-strategy update`
3. Check source file and see that quotes have been removed from descriptions

**Expected behaviour**
I would expect it to leave existing descriptions untouched

**Desktop (please complete the following information):**

- OS: macOS 13.1 (22C65)
- dbt-core==1.3.0
- dbt-coves==1.3.0a18
- dbt-extractor==0.4.1
- dbt-snowflake==1.3.0
- Snowflake 7.1.1
- python 3.9.16

**Comment by jaredx435k2d0** [comment]
Just wanted to check in on this as this seems like an awesome project, but this one hiccup could necessitate a lot of manual intervention and therefore heavily reduce it's positive impact.

We'd absolutely love to implement this as it looks like it fits our exact need!

**Comment by noel** [comment]
@jaredx435k2d0 We would be open to a PR if that is what you are suggesting.  We have a fix for this exact problem, but I am not sure it covers all cases and I am not sure how users would feel about the updated behavior.

Given this 
```
version: 2
sources:
  - name: my_source_name
    database: my_database_name
    description: 'here is a test source description'
    tables:
      - name: my_table_name
        description: 'here is a test table description'
      - name: my_table_name2
        description: here is a test table description
      - name: my_table_name3
        description: customer
```
We would output
```
version: 2
sources:
  - name: my_source_name
    database: my_database_name
    description: 'here is a test source description'
    tables:
      - name: my_table_name
        description: "here is a test table description"
      - name: my_table_name2
        description: "here is a test table description"
      - name: my_table_name3
        description: customer
```

So basically if there are any spaces, then the string is enclosed in `"` but would someone expect that or would the expect the same output as the input?

The other problem I had @BAntonellini look into is what happens with a multi line string.
```
version: 2
sources:
  - name: my_source_name
    database: my_database_name
    description: 'here is a test source description'
    tables:
      - name: my_table_name
        description: >
            here is a test table description
            that is really long
```
this would update to
```
version: 2
sources:
  - name: my_source_name
    database: my_database_name
    description: 'here is a test source description'
    tables:
      - name: my_table_name
        description: "here is a test table description\
            \ that is really long \n"
```
This IMO is not something a user would expect.

The problem occurs in how we handle the original file. We parse the yml and in that step we lose the formatting. 

Any ideas/suggestions welcomed.
