### ISSUE TITLE
[BUG] (question) `generate sources` doesn't pick up new columns

### ISSUE THREAD

**Issue by jaredx435k2d0** [datacoves/dbt-coves#316]
**Describe the bug**
If I run `generate sources`, then add a column to one of the tables for which the sources were created, then re-run `generate sources`, the new column is not picked up. I'm not sure if this is expected or not.

**To Reproduce**
Steps to reproduce the behaviour:

1. Run `generate sources`
2. In the database, add a column to one of the source tables
3. Run `generate sources` again

**Expected behaviour**
I would expect that the new column would be added in the sources.yml file (and for it to potentially remove dropped columns).

**Console Log/Tracebacks**
Please avoid screenshots if possible, instead copy and paste the console and wrap it in
`code by using`code block` `
**Desktop (please complete the following information):**

- OS: macOS 13.2 (22D49)
- Snowflake 7.3.1
- Python 3.10.9
- dbt-core==1.3.2
- dbt-coves==1.3.0a25
- dbt-extractor==0.4.1
- dbt-snowflake==1.3.0

**Comment by BAntonellini** [comment]
@jaredx435k2d0 source property files don't contemplate columns

```yaml
version: 2

sources:
  - name: SOURCE_NAME
    database: DB
    tables:
      - name: TABLE
        description: ''
      - name: TABLE
        description: ''
      - name: TABLE
        description: ''
```

What in fact does contemplate column names, and updated in subsequent passes of `generate sources`, are staging models

In the example below I had `file` and `id` as my model columns, added 2 `test_col` ones in Snowflake, and re-ran `generate sources` with `update` as strategy.

```yaml
version: 2

models:
  - name: MY_MODEL
    description: ''
    columns:
      - name: file
      - name: id
      - name: test_col
      - name: test_col_2

```
