### ISSUE TITLE
[BUG] Precommit config installed in `['.']` folder

### ISSUE THREAD

**Issue by mjkanji** [datacoves/dbt-coves#446]
**Describe the bug**
Maybe this is intended (in which case it's a rather unusual choice), but when I ran `dbt-coves setup precommit`, it created all of the config files inside a `['.']` folder. See the tree below:

```bash
├── ['.']
│   ├── .dbt-coves-precommit.yaml
│   ├── .sqlfluff
│   ├── .sqlfluffignore
│   └── .yamllint
├── pre-commit-config.yaml
```

The only file that's in the root directory is `pre-commit-config.yaml`. This file's contents also have many references to the same folder:

<details><summary>pre-commit-config.yaml</summary>
<p>

```yaml
files: ^['.']/models/

repos:
  - repo: https://github.com/dbt-checkpoint/dbt-checkpoint
    rev: v1.0.0

    hooks:
      - id: dbt-docs-generate
        args: ["--cmd-flags", "++project+dir", "['.']", "++no+compile"]
      - id: check-source-table-has-description
        files: ^['.']/models/

      - id: check-script-semicolon
      - id: check-script-has-no-table-name
      - id: check-script-ref-and-source
        args: ["--manifest", "['.']/target/manifest.json"]
      - id: check-model-has-description
        args: ["--manifest", "['.']/target/manifest.json"]
      - id: check-model-has-properties-file
        args: ["--manifest", "['.']/target/manifest.json"]

      # This does not work with deferral because dbt docs generate does not include models that dont exist in current db
      - id: check-model-has-all-columns
        args:
          [
            "--manifest",
            "['.']/target/manifest.json",
            "--catalog",
            "['.']/target/catalog.json",
          ]

  - repo: https://github.com/sqlfluff/sqlfluff
    # this is the version of sqlfluff, needs to be updated when using a new sqlfluff version (pip show sqlfluff)
    rev: 2.0.3
    hooks:
      - id: sqlfluff-lint
        language: python
        # Need these two dependencies.
        #   sqlfluff-templater-dbt should match the version of sqlfluff above in rev (pip show sqlfluff-templater-dbt)
        #   dbt-snowflake needs to match the version in ['.'] tab of Datacoves (pip show dbt-snowflake)
        additional_dependencies:
          ["sqlfluff-templater-dbt==2.0.3", "dbt-snowflake==1.3.1"]
        args: [--config, ['.']/.sqlfluff]

  - repo: https://github.com/adrienverge/yamllint.git
    rev: v1.17.0
    hooks:
      - id: yamllint
        args: [-c=.yamllint]
        exclude: ^['.']/.dbt_coves/templates

```

</p>
</details>

Having a folder with symbols in its name is a very unusual choice (and makes it very hard to refer to the folder in the terminal), so I'm assuming it's a bug?

**To Reproduce**
Steps to reproduce the behaviour:

1. Run `dbt-coves precommit` in a repo.

**Expected behaviour**

**Console Log/Tracebacks**
N/A. It's as simple as running `dbt-coves setup precommit`.

**Desktop (please complete the following information):**

- OS: Linux (via WSL2 in Windows)
- Browser Firefox
- Version `dbt-coves v1.7.2, dbt v1.7.8`

**Additional context**
