### ISSUE TITLE
[BUG] dbt_coves/templates not working as expected

### ISSUE THREAD

**Issue by davidggphy** [datacoves/dbt-coves#495]
**Describe the bug**
I created a custom `model_props.ylm` template, to ensure that all my models enforce the contract.

**To Reproduce**
Steps to reproduce the behaviour:

1. Run command "dbt-coves generate templates"
2. cd into the folder ".dbt_coves/templates/" and edit `model_props.ylm`
```
version: 2

models:
  - name: {{ model.lower() }}
    description: ""
    config:
      contract:
        enforced: true
    columns:
{%- for col in columns %}
      - name: {{ col['id'] }}
      {%- if col['description'] %}
        description: "{{ col['description'] }}"
      {%- endif %}
{%- endfor %}
```
3. Run `dbt-coves generate properties --templates-folder .dbt_coves/templates/ `, select all models and "Update all"

**Expected behaviour**

I would expect that all models would get the following extra lines:
```
    config:
      contract:
        enforced: true
```

**Desktop (please complete the following information):**

- OS: macOS 14.6.1 (23G93)
- dbt-coves Version: 1.8.0
